//Async return begins with RECEIVE_
export const Actions ={
  GET_SOURCES: 'GET_SOURCES',
  GET_ARTICLES: 'GET_ARTICLES',
  SORT_ARTICLES: 'SORT_ARTICLES',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT'
    // SELECT_SEARCH_AGAIN: 'SELECT_SEARCH_AGAIN',
    // RECEIVE_SEARCH_QUERY:'RECEIVE_SEARCH_QUERY',
    // SEARCH_QUERY:'SEARCH_QUERY'
};

export const ViewFilters = {
  SEARCHING: 'SEARCHING',
  RESULTS: 'RESULTS',
};
