export const Actions = {
  GET_SOURCES: 'GET_SOURCES',
  GET_ARTICLES: 'GET_ARTICLES',
  SORT_ARTICLES: 'SORT_ARTICLES',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT'
};

export const ViewFilters = {
  SEARCHING: 'SEARCHING',
  RESULTS: 'RESULTS',
};
